Add lbfgs for numerical minimization.
Remove unnecessary code and empty list in `get_doc_classes()` function.

Add LBFGSBSolver class and register it

Add LBFGSBSolver and LBFGSSolver classes

Add LBFGSBSolver and LBFGSSolver classes

Remove LBFGSSolver class and update LBFGSBSolver documentation

Add whitespace.

Update defines.

Refactor documentation for improved readability and clarity

Refactor lbfgs module paths and include third-party lbfgsbpp

error: declaration of 'ft' shadows a previous local

Avoid shadowing.

Add TASKING_INTERNAL and _USE_MATH_DEFINES defines to env_lbfgs

Refactor LBFGSBSolver::minimize function for better error handling

Update include path for LBFGSpp library

Refactor .gitignore: Remove unnecessary files and directories

Change gitignore_check.sh to use case-sensitive matching for git check-ignore command

Invalid minimize condition.

Modify gitignore to keep module thirdparty files.

Change LBFGSBSolver to be a node since it requires a frame delta.

Update LBFGSBSolver to be a node.

Refactor LBFGSBSolver.xml: Add vararg qualifiers to minimize method

Refactor LBFGSBSolver.xml to remove unnecessary vararg qualifier in the minimize method

Delete unused macOS editor object file

Remove unnecessary lines from .gitignore files

Ignores are conflicting.

LBFGSBSolver : public RefCounted

Update solver.

Refactor SCsub to use direct import of env module

Delete.

git subrepo clone https://github.com/V-Sekai/godot-lbfgs.git modules/lbfgs

subrepo:
  subdir:   "modules/lbfgs"
  merged:   "a0a669c4bf"
upstream:
  origin:   "https://github.com/V-Sekai/godot-lbfgs.git"
  branch:   "main"
  commit:   "a0a669c4bf"
git-subrepo:
  version:  "0.4.9"
  origin:   "https://github.com/ingydotnet/git-subrepo"
  commit:   "cce3d93"